import { ShowcaseSlide } from "@/components/home/product-showcase-carousel/types"

export const showcaseSlides: ShowcaseSlide[] = [
  {
    id: "hero-refrigeracao",
    title: "Tudo para refrigeração em um só lugar",
    description: "Produtos de qualidade para profissionais de refrigeração e climatização.",
    ctaText: "Ver produtos",
    ctaLink: "/br/categories",
    href: "/br/categories",
    imageFilename: "hero-refrigeracao.png",
    imageDesktop: "/images/carousel/hero-refrigeracao.png",
    alt: "Tudo para refrigeração em um só lugar",
    isPromotionalImage: true,
    hideOverlayContent: true,
    imageFit: "cover",
    objectPosition: "50% 45%",
    objectPositionMobile: "left center",
  },
  {
    id: "hero-entrega-sao-paulo",
    title: "Entrega rápida em São Paulo",
    description: "Motoboy em diversas regiões e frete grátis nas rotas do veículo próprio.",
    ctaText: "Consulte seu CEP",
    ctaLink: "/br/categories",
    href: "/br/categories",
    imageFilename: "hero-entrega-sao-paulo.png",
    imageDesktop: "/images/carousel/hero-entrega-sao-paulo.png",
    alt: "Entrega rápida em São Paulo",
    isPromotionalImage: true,
    hideOverlayContent: true,
    imageFit: "cover",
    objectPosition: "50% 40%",
    objectPositionMobile: "left center",
  },
  {
    id: "hero-atendimento-tecnico",
    title: "Atendimento técnico especializado",
    description: "Ajudamos você a encontrar a solução certa para o seu projeto.",
    ctaText: "Fale com um especialista",
    ctaLink: "/br/categories",
    href: "/br/categories",
    imageFilename: "hero-atendimento-tecnico.png",
    imageDesktop: "/images/carousel/hero-atendimento-tecnico.png",
    alt: "Atendimento técnico especializado",
    isPromotionalImage: true,
    hideOverlayContent: true,
    imageFit: "cover",
    objectPosition: "50% 20%",
    objectPositionMobile: "left center",
  },
]
