server {
    listen 80;
    server_name api.friggafrio.com.br www.friggafrio.com.br friggafrio.com.br admin.friggafrio.com.br;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

# --- STOREFRONT (Frontend) ---
server {
    listen 443 ssl;
    server_name www.friggafrio.com.br friggafrio.com.br;

    # NOTA: O Certbot precisará gerar o certificado cobrindo ambos domínios base
    ssl_certificate /etc/letsencrypt/live/friggafrio.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/friggafrio.com.br/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    location / {
        # Redireciona o tráfego 443/80 do site principal para o container 'storefront' interno
        proxy_pass http://storefront:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# --- BACKEND (API) ---
server {
    listen 443 ssl;
    server_name api.friggafrio.com.br;

    ssl_certificate /etc/letsencrypt/live/api.friggafrio.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.friggafrio.com.br/privkey.pem;

    # Configurações de segurança recomendadas para SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    location / {
        proxy_pass http://backend:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
