/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CountryCodeRouteImport } from './routes/$countryCode'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CountryCodeIndexRouteImport } from './routes/$countryCode/index'
import { Route as CountryCodeTrocasRouteImport } from './routes/$countryCode/trocas'
import { Route as CountryCodeTermosRouteImport } from './routes/$countryCode/termos'
import { Route as CountryCodeStoreRouteImport } from './routes/$countryCode/store'
import { Route as CountryCodeQuotesRouteImport } from './routes/$countryCode/quotes'
import { Route as CountryCodeQuemSomosRouteImport } from './routes/$countryCode/quem-somos'
import { Route as CountryCodePrivacidadeRouteImport } from './routes/$countryCode/privacidade'
import { Route as CountryCodeNossaLojaRouteImport } from './routes/$countryCode/nossa-loja'
import { Route as CountryCodeHealthRouteImport } from './routes/$countryCode/health'
import { Route as CountryCodeEmployeesRouteImport } from './routes/$countryCode/employees'
import { Route as CountryCodeCheckoutRouteImport } from './routes/$countryCode/checkout'
import { Route as CountryCodeCartRouteImport } from './routes/$countryCode/cart'
import { Route as CountryCodeAjudaRouteImport } from './routes/$countryCode/ajuda'
import { Route as CountryCodeAccountIndexRouteImport } from './routes/$countryCode/account/index'
import { Route as CountryCodeProductsHandleRouteImport } from './routes/$countryCode/products/$handle'
import { Route as CountryCodeCategoriesHandleRouteImport } from './routes/$countryCode/categories/$handle'
import { Route as CountryCodeAccountRegisterRouteImport } from './routes/$countryCode/account/register'
import { Route as CountryCodeAccountOrdersRouteImport } from './routes/$countryCode/account/orders'
import { Route as CountryCodeAccountLoginRouteImport } from './routes/$countryCode/account/login'
import { Route as CountryCodeAccountAcceptInviteRouteImport } from './routes/$countryCode/account/accept-invite'
import { Route as CountryCodeOrderOrderIdPaymentRouteImport } from './routes/$countryCode/order/$orderId/payment'
import { Route as CountryCodeOrderOrderIdConfirmedRouteImport } from './routes/$countryCode/order/$orderId/confirmed'

const CountryCodeRoute = CountryCodeRouteImport.update({
  id: '/$countryCode',
  path: '/$countryCode',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountryCodeIndexRoute = CountryCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeTrocasRoute = CountryCodeTrocasRouteImport.update({
  id: '/trocas',
  path: '/trocas',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeTermosRoute = CountryCodeTermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeStoreRoute = CountryCodeStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeQuotesRoute = CountryCodeQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeQuemSomosRoute = CountryCodeQuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodePrivacidadeRoute = CountryCodePrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeNossaLojaRoute = CountryCodeNossaLojaRouteImport.update({
  id: '/nossa-loja',
  path: '/nossa-loja',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeHealthRoute = CountryCodeHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeEmployeesRoute = CountryCodeEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeCheckoutRoute = CountryCodeCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeCartRoute = CountryCodeCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeAjudaRoute = CountryCodeAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeAccountIndexRoute = CountryCodeAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeProductsHandleRoute =
  CountryCodeProductsHandleRouteImport.update({
    id: '/products/$handle',
    path: '/products/$handle',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeCategoriesHandleRoute =
  CountryCodeCategoriesHandleRouteImport.update({
    id: '/categories/$handle',
    path: '/categories/$handle',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeAccountRegisterRoute =
  CountryCodeAccountRegisterRouteImport.update({
    id: '/account/register',
    path: '/account/register',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeAccountOrdersRoute =
  CountryCodeAccountOrdersRouteImport.update({
    id: '/account/orders',
    path: '/account/orders',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeAccountLoginRoute = CountryCodeAccountLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => CountryCodeRoute,
} as any)
const CountryCodeAccountAcceptInviteRoute =
  CountryCodeAccountAcceptInviteRouteImport.update({
    id: '/account/accept-invite',
    path: '/account/accept-invite',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeOrderOrderIdPaymentRoute =
  CountryCodeOrderOrderIdPaymentRouteImport.update({
    id: '/order/$orderId/payment',
    path: '/order/$orderId/payment',
    getParentRoute: () => CountryCodeRoute,
  } as any)
const CountryCodeOrderOrderIdConfirmedRoute =
  CountryCodeOrderOrderIdConfirmedRouteImport.update({
    id: '/order/$orderId/confirmed',
    path: '/order/$orderId/confirmed',
    getParentRoute: () => CountryCodeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$countryCode': typeof CountryCodeRouteWithChildren
  '/$countryCode/ajuda': typeof CountryCodeAjudaRoute
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/employees': typeof CountryCodeEmployeesRoute
  '/$countryCode/health': typeof CountryCodeHealthRoute
  '/$countryCode/nossa-loja': typeof CountryCodeNossaLojaRoute
  '/$countryCode/privacidade': typeof CountryCodePrivacidadeRoute
  '/$countryCode/quem-somos': typeof CountryCodeQuemSomosRoute
  '/$countryCode/quotes': typeof CountryCodeQuotesRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/$countryCode/termos': typeof CountryCodeTermosRoute
  '/$countryCode/trocas': typeof CountryCodeTrocasRoute
  '/$countryCode/': typeof CountryCodeIndexRoute
  '/$countryCode/account/accept-invite': typeof CountryCodeAccountAcceptInviteRoute
  '/$countryCode/account/login': typeof CountryCodeAccountLoginRoute
  '/$countryCode/account/orders': typeof CountryCodeAccountOrdersRoute
  '/$countryCode/account/register': typeof CountryCodeAccountRegisterRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/$countryCode/account/': typeof CountryCodeAccountIndexRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeOrderOrderIdConfirmedRoute
  '/$countryCode/order/$orderId/payment': typeof CountryCodeOrderOrderIdPaymentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$countryCode/ajuda': typeof CountryCodeAjudaRoute
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/employees': typeof CountryCodeEmployeesRoute
  '/$countryCode/health': typeof CountryCodeHealthRoute
  '/$countryCode/nossa-loja': typeof CountryCodeNossaLojaRoute
  '/$countryCode/privacidade': typeof CountryCodePrivacidadeRoute
  '/$countryCode/quem-somos': typeof CountryCodeQuemSomosRoute
  '/$countryCode/quotes': typeof CountryCodeQuotesRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/$countryCode/termos': typeof CountryCodeTermosRoute
  '/$countryCode/trocas': typeof CountryCodeTrocasRoute
  '/$countryCode': typeof CountryCodeIndexRoute
  '/$countryCode/account/accept-invite': typeof CountryCodeAccountAcceptInviteRoute
  '/$countryCode/account/login': typeof CountryCodeAccountLoginRoute
  '/$countryCode/account/orders': typeof CountryCodeAccountOrdersRoute
  '/$countryCode/account/register': typeof CountryCodeAccountRegisterRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/$countryCode/account': typeof CountryCodeAccountIndexRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeOrderOrderIdConfirmedRoute
  '/$countryCode/order/$orderId/payment': typeof CountryCodeOrderOrderIdPaymentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$countryCode': typeof CountryCodeRouteWithChildren
  '/$countryCode/ajuda': typeof CountryCodeAjudaRoute
  '/$countryCode/cart': typeof CountryCodeCartRoute
  '/$countryCode/checkout': typeof CountryCodeCheckoutRoute
  '/$countryCode/employees': typeof CountryCodeEmployeesRoute
  '/$countryCode/health': typeof CountryCodeHealthRoute
  '/$countryCode/nossa-loja': typeof CountryCodeNossaLojaRoute
  '/$countryCode/privacidade': typeof CountryCodePrivacidadeRoute
  '/$countryCode/quem-somos': typeof CountryCodeQuemSomosRoute
  '/$countryCode/quotes': typeof CountryCodeQuotesRoute
  '/$countryCode/store': typeof CountryCodeStoreRoute
  '/$countryCode/termos': typeof CountryCodeTermosRoute
  '/$countryCode/trocas': typeof CountryCodeTrocasRoute
  '/$countryCode/': typeof CountryCodeIndexRoute
  '/$countryCode/account/accept-invite': typeof CountryCodeAccountAcceptInviteRoute
  '/$countryCode/account/login': typeof CountryCodeAccountLoginRoute
  '/$countryCode/account/orders': typeof CountryCodeAccountOrdersRoute
  '/$countryCode/account/register': typeof CountryCodeAccountRegisterRoute
  '/$countryCode/categories/$handle': typeof CountryCodeCategoriesHandleRoute
  '/$countryCode/products/$handle': typeof CountryCodeProductsHandleRoute
  '/$countryCode/account/': typeof CountryCodeAccountIndexRoute
  '/$countryCode/order/$orderId/confirmed': typeof CountryCodeOrderOrderIdConfirmedRoute
  '/$countryCode/order/$orderId/payment': typeof CountryCodeOrderOrderIdPaymentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/$countryCode'
    | '/$countryCode/ajuda'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/employees'
    | '/$countryCode/health'
    | '/$countryCode/nossa-loja'
    | '/$countryCode/privacidade'
    | '/$countryCode/quem-somos'
    | '/$countryCode/quotes'
    | '/$countryCode/store'
    | '/$countryCode/termos'
    | '/$countryCode/trocas'
    | '/$countryCode/'
    | '/$countryCode/account/accept-invite'
    | '/$countryCode/account/login'
    | '/$countryCode/account/orders'
    | '/$countryCode/account/register'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/products/$handle'
    | '/$countryCode/account/'
    | '/$countryCode/order/$orderId/confirmed'
    | '/$countryCode/order/$orderId/payment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/$countryCode/ajuda'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/employees'
    | '/$countryCode/health'
    | '/$countryCode/nossa-loja'
    | '/$countryCode/privacidade'
    | '/$countryCode/quem-somos'
    | '/$countryCode/quotes'
    | '/$countryCode/store'
    | '/$countryCode/termos'
    | '/$countryCode/trocas'
    | '/$countryCode'
    | '/$countryCode/account/accept-invite'
    | '/$countryCode/account/login'
    | '/$countryCode/account/orders'
    | '/$countryCode/account/register'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/products/$handle'
    | '/$countryCode/account'
    | '/$countryCode/order/$orderId/confirmed'
    | '/$countryCode/order/$orderId/payment'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/$countryCode'
    | '/$countryCode/ajuda'
    | '/$countryCode/cart'
    | '/$countryCode/checkout'
    | '/$countryCode/employees'
    | '/$countryCode/health'
    | '/$countryCode/nossa-loja'
    | '/$countryCode/privacidade'
    | '/$countryCode/quem-somos'
    | '/$countryCode/quotes'
    | '/$countryCode/store'
    | '/$countryCode/termos'
    | '/$countryCode/trocas'
    | '/$countryCode/'
    | '/$countryCode/account/accept-invite'
    | '/$countryCode/account/login'
    | '/$countryCode/account/orders'
    | '/$countryCode/account/register'
    | '/$countryCode/categories/$handle'
    | '/$countryCode/products/$handle'
    | '/$countryCode/account/'
    | '/$countryCode/order/$orderId/confirmed'
    | '/$countryCode/order/$orderId/payment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CountryCodeRoute: typeof CountryCodeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$countryCode': {
      id: '/$countryCode'
      path: '/$countryCode'
      fullPath: '/$countryCode'
      preLoaderRoute: typeof CountryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$countryCode/': {
      id: '/$countryCode/'
      path: '/'
      fullPath: '/$countryCode/'
      preLoaderRoute: typeof CountryCodeIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/trocas': {
      id: '/$countryCode/trocas'
      path: '/trocas'
      fullPath: '/$countryCode/trocas'
      preLoaderRoute: typeof CountryCodeTrocasRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/termos': {
      id: '/$countryCode/termos'
      path: '/termos'
      fullPath: '/$countryCode/termos'
      preLoaderRoute: typeof CountryCodeTermosRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/store': {
      id: '/$countryCode/store'
      path: '/store'
      fullPath: '/$countryCode/store'
      preLoaderRoute: typeof CountryCodeStoreRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/quotes': {
      id: '/$countryCode/quotes'
      path: '/quotes'
      fullPath: '/$countryCode/quotes'
      preLoaderRoute: typeof CountryCodeQuotesRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/quem-somos': {
      id: '/$countryCode/quem-somos'
      path: '/quem-somos'
      fullPath: '/$countryCode/quem-somos'
      preLoaderRoute: typeof CountryCodeQuemSomosRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/privacidade': {
      id: '/$countryCode/privacidade'
      path: '/privacidade'
      fullPath: '/$countryCode/privacidade'
      preLoaderRoute: typeof CountryCodePrivacidadeRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/nossa-loja': {
      id: '/$countryCode/nossa-loja'
      path: '/nossa-loja'
      fullPath: '/$countryCode/nossa-loja'
      preLoaderRoute: typeof CountryCodeNossaLojaRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/health': {
      id: '/$countryCode/health'
      path: '/health'
      fullPath: '/$countryCode/health'
      preLoaderRoute: typeof CountryCodeHealthRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/employees': {
      id: '/$countryCode/employees'
      path: '/employees'
      fullPath: '/$countryCode/employees'
      preLoaderRoute: typeof CountryCodeEmployeesRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/checkout': {
      id: '/$countryCode/checkout'
      path: '/checkout'
      fullPath: '/$countryCode/checkout'
      preLoaderRoute: typeof CountryCodeCheckoutRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/cart': {
      id: '/$countryCode/cart'
      path: '/cart'
      fullPath: '/$countryCode/cart'
      preLoaderRoute: typeof CountryCodeCartRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/ajuda': {
      id: '/$countryCode/ajuda'
      path: '/ajuda'
      fullPath: '/$countryCode/ajuda'
      preLoaderRoute: typeof CountryCodeAjudaRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/': {
      id: '/$countryCode/account/'
      path: '/account'
      fullPath: '/$countryCode/account/'
      preLoaderRoute: typeof CountryCodeAccountIndexRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/products/$handle': {
      id: '/$countryCode/products/$handle'
      path: '/products/$handle'
      fullPath: '/$countryCode/products/$handle'
      preLoaderRoute: typeof CountryCodeProductsHandleRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/categories/$handle': {
      id: '/$countryCode/categories/$handle'
      path: '/categories/$handle'
      fullPath: '/$countryCode/categories/$handle'
      preLoaderRoute: typeof CountryCodeCategoriesHandleRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/register': {
      id: '/$countryCode/account/register'
      path: '/account/register'
      fullPath: '/$countryCode/account/register'
      preLoaderRoute: typeof CountryCodeAccountRegisterRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/orders': {
      id: '/$countryCode/account/orders'
      path: '/account/orders'
      fullPath: '/$countryCode/account/orders'
      preLoaderRoute: typeof CountryCodeAccountOrdersRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/login': {
      id: '/$countryCode/account/login'
      path: '/account/login'
      fullPath: '/$countryCode/account/login'
      preLoaderRoute: typeof CountryCodeAccountLoginRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/account/accept-invite': {
      id: '/$countryCode/account/accept-invite'
      path: '/account/accept-invite'
      fullPath: '/$countryCode/account/accept-invite'
      preLoaderRoute: typeof CountryCodeAccountAcceptInviteRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/order/$orderId/payment': {
      id: '/$countryCode/order/$orderId/payment'
      path: '/order/$orderId/payment'
      fullPath: '/$countryCode/order/$orderId/payment'
      preLoaderRoute: typeof CountryCodeOrderOrderIdPaymentRouteImport
      parentRoute: typeof CountryCodeRoute
    }
    '/$countryCode/order/$orderId/confirmed': {
      id: '/$countryCode/order/$orderId/confirmed'
      path: '/order/$orderId/confirmed'
      fullPath: '/$countryCode/order/$orderId/confirmed'
      preLoaderRoute: typeof CountryCodeOrderOrderIdConfirmedRouteImport
      parentRoute: typeof CountryCodeRoute
    }
  }
}

interface CountryCodeRouteChildren {
  CountryCodeAjudaRoute: typeof CountryCodeAjudaRoute
  CountryCodeCartRoute: typeof CountryCodeCartRoute
  CountryCodeCheckoutRoute: typeof CountryCodeCheckoutRoute
  CountryCodeEmployeesRoute: typeof CountryCodeEmployeesRoute
  CountryCodeHealthRoute: typeof CountryCodeHealthRoute
  CountryCodeNossaLojaRoute: typeof CountryCodeNossaLojaRoute
  CountryCodePrivacidadeRoute: typeof CountryCodePrivacidadeRoute
  CountryCodeQuemSomosRoute: typeof CountryCodeQuemSomosRoute
  CountryCodeQuotesRoute: typeof CountryCodeQuotesRoute
  CountryCodeStoreRoute: typeof CountryCodeStoreRoute
  CountryCodeTermosRoute: typeof CountryCodeTermosRoute
  CountryCodeTrocasRoute: typeof CountryCodeTrocasRoute
  CountryCodeIndexRoute: typeof CountryCodeIndexRoute
  CountryCodeAccountAcceptInviteRoute: typeof CountryCodeAccountAcceptInviteRoute
  CountryCodeAccountLoginRoute: typeof CountryCodeAccountLoginRoute
  CountryCodeAccountOrdersRoute: typeof CountryCodeAccountOrdersRoute
  CountryCodeAccountRegisterRoute: typeof CountryCodeAccountRegisterRoute
  CountryCodeCategoriesHandleRoute: typeof CountryCodeCategoriesHandleRoute
  CountryCodeProductsHandleRoute: typeof CountryCodeProductsHandleRoute
  CountryCodeAccountIndexRoute: typeof CountryCodeAccountIndexRoute
  CountryCodeOrderOrderIdConfirmedRoute: typeof CountryCodeOrderOrderIdConfirmedRoute
  CountryCodeOrderOrderIdPaymentRoute: typeof CountryCodeOrderOrderIdPaymentRoute
}

const CountryCodeRouteChildren: CountryCodeRouteChildren = {
  CountryCodeAjudaRoute: CountryCodeAjudaRoute,
  CountryCodeCartRoute: CountryCodeCartRoute,
  CountryCodeCheckoutRoute: CountryCodeCheckoutRoute,
  CountryCodeEmployeesRoute: CountryCodeEmployeesRoute,
  CountryCodeHealthRoute: CountryCodeHealthRoute,
  CountryCodeNossaLojaRoute: CountryCodeNossaLojaRoute,
  CountryCodePrivacidadeRoute: CountryCodePrivacidadeRoute,
  CountryCodeQuemSomosRoute: CountryCodeQuemSomosRoute,
  CountryCodeQuotesRoute: CountryCodeQuotesRoute,
  CountryCodeStoreRoute: CountryCodeStoreRoute,
  CountryCodeTermosRoute: CountryCodeTermosRoute,
  CountryCodeTrocasRoute: CountryCodeTrocasRoute,
  CountryCodeIndexRoute: CountryCodeIndexRoute,
  CountryCodeAccountAcceptInviteRoute: CountryCodeAccountAcceptInviteRoute,
  CountryCodeAccountLoginRoute: CountryCodeAccountLoginRoute,
  CountryCodeAccountOrdersRoute: CountryCodeAccountOrdersRoute,
  CountryCodeAccountRegisterRoute: CountryCodeAccountRegisterRoute,
  CountryCodeCategoriesHandleRoute: CountryCodeCategoriesHandleRoute,
  CountryCodeProductsHandleRoute: CountryCodeProductsHandleRoute,
  CountryCodeAccountIndexRoute: CountryCodeAccountIndexRoute,
  CountryCodeOrderOrderIdConfirmedRoute: CountryCodeOrderOrderIdConfirmedRoute,
  CountryCodeOrderOrderIdPaymentRoute: CountryCodeOrderOrderIdPaymentRoute,
}

const CountryCodeRouteWithChildren = CountryCodeRoute._addFileChildren(
  CountryCodeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CountryCodeRoute: CountryCodeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
